spring:
  elasticjob:

    datasource:
      url: jdbc:mysql://127.0.0.1:3306/elasticjob_log?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123123
      # 是否载数据库
      enable: true
    regCenter:
      serverList: 127.0.0.1:2181
      namespace: elasticJobDemo
    scheduled:
      jobConfigMap:
        myJobConfig:
          jobName: myJobConfig
          cron: 123
          shardingTotalCount: 1
          shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
          jobParameters: 1
        youJobConfig:
          jobName: youJobConfig
          cron: 123
          shardingTotalCount: 1
          shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
          jobParameters: 1
        PropertiesSimpleJob:
          jobName: PropertiesSimpleJob
          cron: 0 0/1 * * * ?
          shardingTotalCount: 1
          shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
          jobParameters: test